[package]
name = "planner-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.8"
tempfile = "3.2.0"
